name: Clean Up Old Images

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
  schedule:
    - cron: '*/30 * * * *'

jobs:
  clean-up-images:
    runs-on: ubuntu-latest

    steps:
      - name: Clean up old images using curl
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPO: osteolab/pictograph_bonecheck
        run: |
          echo "Fetching list of .png files from the repo root..."

          response=$(curl -s -H "Authorization: token $GITHUB_TOKEN" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/$REPO/contents/)

          png_files=$(echo "$response" | jq -r '.[] | select(.name | endswith(".png")) | "\(.name) \(.path) \(.sha)"')

          total=$(echo "$png_files" | wc -l)
          echo "Total .png files: $total"

          if [ "$total" -le 10 ]; then
            echo "No cleanup needed (10 or fewer images)."
            exit 0
          fi

          echo "$png_files" | sort -r | tail -n +11 | while read name path sha; do
            echo "Deleting $name..."

            curl -s -X DELETE \
              -H "Authorization: token $GITHUB_TOKEN" \
              -H "Accept: application/vnd.github.v3+json" \
              -d "{\"message\":\"Delete old image $name\",\"sha\":\"$sha\"}" \
              https://api.github.com/repos/$REPO/contents/$path
          done
